---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relayer-exporter.fullname" . }}-config
  labels:
    {{- include "relayer-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
