apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{include "endpoint-controller.serviceAccountName" .}}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "endpoint-controller.serviceAccountName" .}}
subjects:
- kind: ServiceAccount
  name: {{include "endpoint-controller.serviceAccountName" .}}
  namespace: {{ template "endpoint-controller.namespace" . }} 
roleRef:
  kind: ClusterRole
  name: {{include "endpoint-controller.serviceAccountName" .}}
  apiGroup: rbac.authorization.k8s.io
