{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "endpoint-controller.serviceAccountName" . }}
  namespace: {{ template "endpoint-controller.namespace" . }} 
  labels:
    {{- include "endpoint-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "endpoint-controller.serviceAccountName" . }}
  namespace: {{ template "endpoint-controller.namespace" . }} 
  annotations:
    kubernetes.io/service-account.name: {{ include "endpoint-controller.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
