---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hermes-relayer.fullname" . }}
  namespace: {{ include "hermes-relayer.namespace" . }} 
  labels:
    {{- include "hermes-relayer.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
  selector:
    matchLabels:
      {{- include "hermes-relayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hermes-relayer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: chain1mnenomic
        secret:
          secretName: {{ .Values.relayer.chain1SecretName }}
      - name: chain2mnenomic
        secret:
          secretName: {{ .Values.relayer.chain2SecretName }}
      - name: keys
        emptyDir: {}
      - name: configfile
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
            - key: config.toml
              path: config.toml
      initContainers:
        - name: init-chain-1
          image: "{{.Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          args: [
            'keys',
            'add',
            '--chain',
            '{{ .Values.relayer.chain1ID }}',
            '--mnemonic-file',
            '/etc/mnemonic/mnemonic'
          ]
          volumeMounts:
            - name: keys
              mountPath: "/home/hermes/.hermes/keys"
            - name: configfile
              mountPath: "/home/hermes/.hermes/"
            - name: chain1mnenomic
              readOnly: true
              mountPath: /etc/mnemonic
        - name: init-chain-2
          image: "{{.Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          args: [
            'keys',
            'add',
            '--chain',
            '{{ .Values.relayer.chain2ID }}',
            '--mnemonic-file',
            '/etc/mnemonic/mnemonic'
          ]
          volumeMounts:
            - name: keys
              mountPath: "/home/hermes/.hermes/keys"
            - name: configfile
              mountPath: "/home/hermes/.hermes/"
            - name: chain2mnenomic
              readOnly: true
              mountPath: /etc/mnemonic
      containers:
        - name: relayer 
          image: "{{.Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          args: [
            'start'
          ]
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: keys
            mountPath: /home/hermes/.hermes/keys
          - name: configfile
            mountPath: "/home/hermes/.hermes/"
          ports:
          - containerPort: 3001
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
