---
apiVersion: v1
kind: Service
metadata:
  name: {{include "hermes-relayer.fullname" .}}
  namespace: {{include "hermes-relayer.namespace" .}}
  labels:
    {{- include "hermes-relayer.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: telemetry
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    matchLabels:
      {{- include "hermes-relayer.selectorLabels" . | nindent 6 }}
  sessionAffinity: None
  type: ClusterIP
