---
image:
  repository: ghcr.io/archway-network/discord-alertmanager
  pullPolicy: Always
  tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsGroup: 65532
  runAsUser: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false

service:
  type: ClusterIP
  port: 9094

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
# configFile:
#   webhookUrl: ""
#   whitelist: []
#   blacklist: []
#   notifyList: []
#
# envVars:
#   dicordWebhook: ""
#   whitelist: ""
#   blacklist: ""
